### ISSUE TITLE
Bring the project up to parity with Prometheus v2.39.0

### ISSUE THREAD

**Issue by 8BitSensei** [GoogleCloudPlatform/prometheus#19]
## Bring Google managed Prometheus up to parity with Prometheus v2.39.0

**There are fixes and features that have come into Prometheus that would be useful in GMP**

Is there a schedule for GMP to be brought up to parity? The current version of Prometheus used is v2.35.0 from back in April.

**Comment by pintohutch** [comment]
Hi @8BitSensei - thanks for reporting.

I don't have a schedule for you at the moment, but we do have this top-of-mind cc @lyanco.

We can update here when we have something more concrete!

**Comment by lyanco** [comment]
What specific fixes and features from the newer versions would be most useful to you?

**Comment by 8BitSensei** [comment]
Hey @lyanco I'm particularly looking at changes they've made to `kubernetes_sd` which extends the capabilities of service discovery https://github.com/prometheus/prometheus/pull/10759

**Comment by lyanco** [comment]
Noted, thanks! As Danny said, no timeline right now, but we do plan to rebase at some point. Will let you know.

**Comment by 8BitSensei** [comment]
Thanks for the feedback

**Comment by tobiasbrodersen** [comment]
Hey, any update on this? we're also looking to utilize the AttachMetadata field from the prometheus operator

**Comment by lyanco** [comment]
Yes - we've begun the process of cutting an image for 2.41, the first step of which can be seen here: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/483

**Comment by TheSpiritXIII** [comment]
2.41 is now used in the GKE rapid release channel and also the default branch so I'm closing this now. Thanks so much for the bug report! Please open a new one if you need a newer version of Prometheus. We take these requests seriously!
