### ISSUE TITLE
Looks like export.debug.batch-size doesn't have an effect

### ISSUE THREAD

**Issue by kacpercesarz98** [GoogleCloudPlatform/prometheus#196]
### What did you do?

Hello I need to decrease usage of System limit "Service time series ingestion requests per minute" in GCP. To do that I wanted to increase batch-size but it looks like this parameter doesn't change anything. I added bellow extra argument but GCP metrics and logs do not show any change in behaviour.
```
  - name: export.debug.batch-size
    value: '200'
```

### What did you expect to see?

I expected that usage of System limit "Service time series ingestion requests per minute" will be decreased but it looks like this change did not have any effect.

### What did you see instead? Under which circumstances?

No change.

### System information

gke.gcr.io/prometheus-engine/prometheus:v2.45.3-gmp.1-gke.0

### Prometheus version

```text
gke.gcr.io/prometheus-engine/prometheus:v2.45.3-gmp.1-gke.0
```

**Comment by pintohutch** [comment]
Thanks for reporting @kacpercesarz98, I'm going to close this and respond in https://github.com/GoogleCloudPlatform/prometheus-engine/issues/1128
