### ISSUE TITLE
Is there any planning on using debian12 base image?

### ISSUE THREAD

**Issue by ltwongaa** [GoogleCloudPlatform/prometheus#212]
The latest prometheus image seems build from a image with debian 11 image
gke.gcr.io/gke-distroless/libc@sha256:4f834e207f2721977094aeec4c9daee7032c5daec2083c0be97760f4306e4f88
we identify it by looking at the etc/os-release file in the layer.

Also I see the there was a PR switch back on using debian11 image from debian 12 due to image not exist.
And now prometheus is using another set of image that is from gke.gcr.io/gke-distroless/libc which seems the latest image is still in debian11.
( etc/os-release still shows debian11 )

Since debian 11 is end of life now, is there any planning migrating to use a debian12 image?
or if there is any agreement from google on vulnerability patching that it is fine to use the gke-distroless/libc image even it is a with debian11 os?

**Comment by lyanco** [comment]
The plan of record is actually to retire the fork altogether and replace it with OSS Prometheus. This should be doable once we've implemented receiving remote write v2, along with a handful of other smaller tasks.

At that point we can much more easily peg versions to the latest without a ton of requalification,.

We expect this to be ready mid-2025.

**Comment by bwplotka** [comment]
Coincidentally we might be able to fix this before unfork similar to https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1190.

**Comment by bernot-dev** [comment]
Just switching to a Debian 12 base image can be implemented without code changes. We will get this work scheduled.

**Comment by ltwongaa** [comment]
Hi @bernot-dev 
sorry could we reopen this issue?

The base image updated using now
gke.gcr.io/gke-distroless/libc@sha256:92412775c9273849ea1902c6dd9c2fcd4977c14c67949def8d619fb380dc9acd
should still be a debian11 image

It is verified before this issue is created as mentioned in the description

> And now prometheus is using another set of image that is from gke.gcr.io/gke-distroless/libc which seems the latest image is still in debian11.

Thanks

**Comment by bernot-dev** [comment]
The [distroless images](https://github.com/GoogleContainerTools/distroless?tab=readme-ov-file#distroless-container-images) do not actually contain a Linux distribution and by their nature have a narrow attack surface, so `/etc/os-release` is a bit misleading in that regard. But all the same, we'll update to a different image that will show up as Debian 12 in #217.
